import { StyleSheet } from 'react-native';
import type { AppColors } from '@/shared/theme/colors';

const managerFontSize = {
  xs: 10,
  sm: 13,
  base: 15,
  lg: 18,
};

export const createBaseStyles = (colors: AppColors) =>
  StyleSheet.create({
    summaryMetric: {
      width: '31.8%',
      minHeight: 86,
      justifyContent: 'space-between',
      borderRadius: 8,
      padding: 10,
      marginRight: '1.5%',
      marginBottom: 8,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    summaryMetricTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    summaryMarker: {
      width: 22,
      height: 4,
      borderRadius: 4,
    },
    summaryValue: {
      marginTop: 8,
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    summaryLabel: {
      marginTop: 8,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
      textTransform: 'uppercase',
    },
    userStat: {
      flex: 1,
      minHeight: 50,
      justifyContent: 'center',
      borderRadius: 7,
      paddingHorizontal: 4,
      backgroundColor: colors.backgroundSecondary,
      minWidth: 0,
    },
    userStatValue: {
      marginTop: 5,
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    userStatLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
      textAlign: 'center',
    },
  });

export const createManagerDailySummaryStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundSecondary,
    },
    content: {
      padding: 14,
      paddingBottom: 32,
      gap: 12,
    },
    topBar: {
      minHeight: 44,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    brand: {
      fontSize: managerFontSize.lg,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    brandAccent: {
      color: colors.info,
    },
    caption: {
      marginTop: 2,
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.info,
    },
    refreshButton: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 17,
      backgroundColor: colors.infoLight,
    },
    dailyHeader: {
      minHeight: 76,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      borderRadius: 8,
      padding: 14,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    dailyHeaderMain: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      minWidth: 0,
    },
    dailyIcon: {
      width: 42,
      height: 42,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    dailyHeaderText: {
      flex: 1,
      minWidth: 0,
    },
    dailyTitle: {
      marginTop: 4,
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    dateButton: {
      minHeight: 36,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      paddingHorizontal: 10,
      borderRadius: 7,
      backgroundColor: colors.primaryLight,
    },
    dateButtonText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.primary,
    },
    flowNav: {
      minHeight: 42,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      borderRadius: 8,
      paddingHorizontal: 8,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    flowStep: {
      flex: 1,
      minHeight: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      paddingHorizontal: 4,
    },
    flowStepActive: {
      backgroundColor: colors.primary,
    },
    flowStepDisabled: {
      opacity: 0.45,
    },
    flowStepText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textSecondary,
    },
    flowStepTextActive: {
      color: colors.primaryContrast,
    },
    flowStepTextDisabled: {
      color: colors.textQuaternary,
    },
    flowRefresh: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
      backgroundColor: colors.primaryLight,
    },
    dateCard: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 10,
      borderWidth: 1,
      borderColor: colors.border,
    },
    dateHeader: {
      minHeight: 30,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    dateTitleRow: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    dateLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    dateAction: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    changeDateText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textQuaternary,
    },
    summaryCard: {
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    managerInfo: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    managerAvatar: {
      width: 42,
      height: 42,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    managerAvatarText: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.primary,
    },
    managerTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    sectionTitle: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textQuaternary,
    },
    cardTitle: {
      marginTop: 5,
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    cardSubTitle: {
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    linkButton: {
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 7,
      paddingHorizontal: 10,
      backgroundColor: colors.infoLight,
    },
    linkText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.info,
    },
    refreshMetaRow: {
      alignSelf: 'flex-end',
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginTop: 8,
    },
    refreshed: {
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textQuaternary,
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 12,
      marginRight: '-1.5%',
    },
    metricToggle: {
      flexDirection: 'row',
      marginTop: 12,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.backgroundSecondary,
      overflow: 'hidden',
    },
    metricToggleItem: {
      flex: 1,
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    metricToggleItemActive: {
      backgroundColor: colors.primary,
    },
    metricToggleText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    metricToggleTextActive: {
      color: colors.primaryContrast,
    },
    searchRow: {
      height: 44,
      borderRadius: 8,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textPrimary,
      paddingVertical: 0,
    },
    compactStats: {
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 8,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    compactStat: {
      width: '48%',
      minHeight: 44,
      paddingVertical: 8,
      paddingHorizontal: 10,
      borderRadius: 7,
      backgroundColor: colors.backgroundSecondary,
      borderBottomWidth: 2,
      borderBottomColor: colors.borderLight,
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
    },
    compactStatLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    compactStatValue: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    listHeaderRow: {
      minHeight: 28,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 2,
    },
    listHeaderTitle: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    listHeaderMeta: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    userCard: {
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      gap: 10,
    },
    userHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    userIdentity: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    userAvatar: {
      width: 38,
      height: 38,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    userAvatarText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.primary,
    },
    userNameBlock: {
      flex: 1,
      minWidth: 0,
    },
    userName: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    userPosition: {
      marginTop: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    iconActions: {
      flexDirection: 'row',
      gap: 8,
    },
    circleIcon: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: colors.infoLight,
    },
    routeBadge: {
      minHeight: 32,
      borderWidth: 1,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 8,
      overflow: 'hidden',
    },
    routeBadgeText: {
      width: '40%',
      minHeight: 32,
      textAlignVertical: 'center',
      textAlign: 'center',
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      backgroundColor: colors.backgroundSecondary,
    },
    routeText: {
      flex: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    locationText: {
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    userStats: {
      flexDirection: 'row',
      paddingTop: 2,
      gap: 8,
    },
    emptyText: {
      paddingVertical: 20,
      textAlign: 'center',
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    timelineHeader: {
      borderRadius: 8,
      padding: 14,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    timelineTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    timelineTitleText: {
      flex: 1,
      minWidth: 0,
    },
    tabsRow: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    tabItem: {
      flex: 1,
      minHeight: 38,
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    tabItemActive: {
      borderBottomColor: colors.info,
    },
    tabText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textTertiary,
    },
    tabTextActive: {
      color: colors.info,
    },
    dateTitle: {
      paddingHorizontal: 2,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    timeline: {
      paddingLeft: 18,
      gap: 12,
    },
    timelineLine: {
      position: 'absolute',
      left: 24,
      top: 0,
      bottom: 0,
      width: 1,
      backgroundColor: colors.info,
    },
    dayStart: {
      minHeight: 64,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      marginLeft: 14,
      padding: 10,
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    timelineDot: {
      position: 'absolute',
      left: -2,
      width: 18,
      height: 18,
      borderRadius: 9,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    dayStartText: {
      flex: 1,
      minWidth: 0,
    },
    timelineDotSmall: {
      position: 'absolute',
      left: -21,
      top: 24,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.infoLight,
      borderWidth: 2,
      borderColor: colors.info,
    },
    activityCard: {
      marginLeft: 14,
      borderRadius: 8,
      padding: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    activityHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
    },
    activityTitle: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textSecondary,
    },
    activityTime: {
      marginTop: 2,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    duration: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    selfieText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.primary,
    },
    selfiePill: {
      minHeight: 26,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      borderRadius: 7,
      paddingHorizontal: 8,
      backgroundColor: colors.primaryLight,
    },
    dayStartImage: {
      width: 44,
      height: 44,
      borderRadius: 6,
      backgroundColor: colors.borderLight,
    },
    dayStartImagePlaceholder: {
      width: 44,
      height: 44,
      borderRadius: 6,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    outletRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
      marginTop: 8,
    },
    outletName: {
      flex: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    ownerName: {
      maxWidth: '38%',
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    metricGrid: {
      marginTop: 10,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 6,
    },
    metricCell: {
      width: '31.8%',
      minHeight: 54,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 6,
      borderRadius: 7,
      backgroundColor: colors.backgroundSecondary,
    },
    metricValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    metricLabel: {
      marginTop: 3,
      textAlign: 'center',
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    orderScreen: {
      gap: 10,
    },
    orderHero: {
      minHeight: 82,
      paddingHorizontal: 14,
      paddingVertical: 12,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 12,
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
    },
    orderHeroText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderHeroSub: {
      marginTop: 6,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    orderHeroRight: {
      alignItems: 'flex-end',
      minWidth: 92,
    },
    orderHeroValue: {
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.success,
    },
    orderOutlet: {
      paddingHorizontal: 4,
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderCategory: {
      overflow: 'hidden',
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    orderCategoryHeader: {
      minHeight: 42,
      paddingHorizontal: 10,
      paddingVertical: 8,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
    },
    orderCategoryHeaderBlue: {
      backgroundColor: colors.infoLight,
    },
    orderCategoryHeaderMuted: {
      backgroundColor: colors.backgroundSecondary,
    },
    orderCategoryName: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderCategoryMeta: {
      marginTop: 2,
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    orderCategoryValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderLine: {
      paddingHorizontal: 10,
      paddingVertical: 10,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
      backgroundColor: colors.surface,
    },
    orderLineName: {
      fontSize: managerFontSize.xs,
      lineHeight: 15,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderLineMeta: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      flexWrap: 'wrap',
    },
    orderLineMetaText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    orderUnitPill: {
      minHeight: 16,
      paddingHorizontal: 8,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      backgroundColor: colors.borderLight,
    },
    orderUnitPillText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textSecondary,
    },
    orderLineValue: {
      marginLeft: 'auto',
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textSecondary,
    },
    orderSummary: {
      marginTop: 2,
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    orderSummaryHeader: {
      minHeight: 34,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    orderSummaryHeaderText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.primary,
    },
    orderSummaryRow: {
      minHeight: 32,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    orderSummaryLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    orderSummaryValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderDiscountLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.error,
    },
    orderDiscountValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.error,
    },
    orderDivider: {
      height: 1,
      marginVertical: 4,
      backgroundColor: colors.border,
    },
    orderPayableLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.success,
    },
    orderPayableValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.success,
    },
  });
