import { StyleSheet } from 'react-native';
import type { AppColors } from '@/shared/theme/colors';

export const createManagerTargetsBaseStyles = (colors: AppColors) =>
  StyleSheet.create({
    metric: {
      flex: 1,
      minWidth: 0,
    },
    metricValue: {
      fontSize: 12,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    metricLabel: {
      marginTop: 3,
      fontSize: 10,
      fontWeight: '700',
      color: colors.textTertiary,
    },
  });

export const createManagerTargetsStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundSecondary,
    },
    content: {
      padding: 12,
      gap: 10,
      paddingBottom: 28,
      width: '100%',
      alignSelf: 'center',
    },
    contentWide: {
      maxWidth: 760,
      paddingHorizontal: 20,
      paddingTop: 16,
      gap: 12,
    },
    cardsGrid: {
      width: '100%',
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    cardColumn: {
      width: '100%',
    },
    fullWidthRow: {
      width: '100%',
    },
    targetTabs: {
      borderWidth: 1,
      borderColor: colors.borderLight,
      borderRadius: 8,
      flexDirection: 'row',
      backgroundColor: colors.surface,
      padding: 3,
    },
    targetTab: {
      flex: 1,
      minWidth: 0,
      minHeight: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      paddingHorizontal: 6,
    },
    targetTabActive: {
      backgroundColor: colors.primary,
    },
    targetTabText: {
      fontSize: 11,
      fontWeight: '800',
      color: colors.textSecondary,
      textAlign: 'center',
    },
    targetTabTextActive: {
      color: colors.primaryContrast,
    },
    tabEmptyState: {
      minHeight: 180,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.surface,
    },
    tabEmptyTitle: {
      fontSize: 12,
      fontWeight: '900',
      color: colors.textTertiary,
      textAlign: 'center',
    },
    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: 'rgba(0, 0, 0, 0.42)',
    },
    modalDismissArea: {
      flex: 1,
    },
    bottomSheet: {
      maxHeight: '76%',
      minHeight: 300,
      borderTopLeftRadius: 16,
      borderTopRightRadius: 16,
      paddingHorizontal: 16,
      paddingBottom: 24,
      backgroundColor: colors.surface,
    },
    bottomSheetWide: {
      width: '100%',
      maxWidth: 680,
      alignSelf: 'center',
      borderTopLeftRadius: 12,
      borderTopRightRadius: 12,
    },
    sheetHandle: {
      width: 38,
      height: 4,
      alignSelf: 'center',
      borderRadius: 2,
      marginTop: 8,
      marginBottom: 12,
      backgroundColor: colors.border,
    },
    sheetHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingBottom: 14,
    },
    sheetTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    sheetTitle: {
      fontSize: 16,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    sheetSubtitle: {
      marginTop: 3,
      fontSize: 11,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    sheetCloseButton: {
      width: 34,
      height: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: colors.backgroundSecondary,
    },
    breakdownHeader: {
      minHeight: 34,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 10,
      borderRadius: 6,
      backgroundColor: colors.backgroundSecondary,
    },
    breakdownHeaderText: {
      flex: 1,
      fontSize: 9,
      fontWeight: '900',
      textTransform: 'uppercase',
      textAlign: 'right',
      color: colors.textTertiary,
    },
    breakdownNameColumn: {
      flex: 1.5,
      textAlign: 'left',
    },
    breakdownScroll: {
      marginTop: 4,
    },
    breakdownLoading: {
      gap: 8,
      paddingTop: 8,
    },
    breakdownRow: {
      minHeight: 54,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      paddingHorizontal: 10,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    breakdownName: {
      fontSize: 11,
      lineHeight: 15,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    breakdownValue: {
      flex: 1,
      fontSize: 11,
      fontWeight: '900',
      textAlign: 'right',
      color: colors.textSecondary,
    },
    modalEmptyState: {
      minHeight: 180,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 6,
    },
    parentBanner: {
      minHeight: 52,
      borderRadius: 10,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.infoLight,
      borderWidth: 1,
      borderColor: colors.border,
    },
    parentTextWrap: {
      flex: 1,
    },
    parentTitle: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    parentSubtitle: {
      marginTop: 2,
      fontSize: 11,
      fontWeight: '600',
      color: colors.textTertiary,
    },
    drillButton: {
      minHeight: 28,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      borderRadius: 7,
      paddingHorizontal: 8,
      backgroundColor: colors.infoLight,
    },
    metricToolbar: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    metricChip: {
      flex: 1,
      minHeight: 36,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.borderLight,
      paddingHorizontal: 12,
      backgroundColor: colors.surface,
    },
    metricChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    metricChipText: {
      fontSize: 11,
      fontWeight: '900',
      color: colors.textSecondary,
    },
    metricChipTextActive: {
      color: colors.primaryContrast,
    },
    userCard: {
      minHeight: 0,
      borderRadius: 8,
      padding: 14,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
      elevation: 1,
    },
    userCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 9,
      marginBottom: 12,
    },
    cardIdentity: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    cardAccent: {
      width: 4,
      height: 34,
      borderRadius: 2,
      backgroundColor: colors.primary,
    },
    headerActions: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    percentBadge: {
      minHeight: 26,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      paddingHorizontal: 8,
      backgroundColor: `${colors.success}12`,
    },
    percentBadgeText: {
      fontSize: 10,
      fontWeight: '900',
      color: colors.success,
    },
    avatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary + '18',
    },
    avatarText: {
      fontSize: 13,
      fontWeight: '900',
      color: colors.primary,
    },
    userTitleWrap: {
      flex: 1,
      minWidth: 0,
    },
    userName: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    userPosition: {
      marginTop: 2,
      fontSize: 10,
      fontWeight: '600',
      color: colors.textTertiary,
    },
    drillText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textQuaternary,
    },
    performanceBand: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 12,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 11,
      backgroundColor: colors.backgroundSecondary,
    },
    metricDivider: {
      width: 1,
      backgroundColor: colors.borderLight,
    },
    progressMetaRow: {
      marginTop: 8,
      flexDirection: 'row',
      justifyContent: 'flex-end',
      gap: 8,
    },
    progressMetaText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    cardFooter: {
      marginTop: 8,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      justifyContent: 'flex-end',
      paddingTop: 8,
      borderTopWidth: 1,
      borderTopColor: colors.borderLight,
    },
    footerDot: {
      width: 3,
      height: 3,
      borderRadius: 2,
      backgroundColor: colors.textQuaternary,
    },
    rateLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    categoryButton: {
      marginTop: 14,
      minHeight: 26,
      borderRadius: 7,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      backgroundColor: colors.infoLight,
    },
    categoryButtonText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.primary,
    },
    categoryPanel: {
      marginTop: -4,
      borderRadius: 10,
      padding: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      gap: 10,
    },
    categoryPanelHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    categoryPanelTitle: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    categoryPanelSubtitle: {
      marginTop: 2,
      fontSize: 10,
      fontWeight: '600',
      color: colors.textTertiary,
    },
    categoryPanelBadge: {
      borderRadius: 7,
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: colors.infoLight,
      color: colors.primary,
      fontSize: 10,
      fontWeight: '900',
      overflow: 'hidden',
    },
    categoryRow: {
      borderRadius: 8,
      padding: 10,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    categoryRowTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    categoryName: {
      flex: 1,
      fontSize: 12,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    categoryPercent: {
      fontSize: 10,
      fontWeight: '900',
      color: colors.primary,
    },
    categoryMetricsGrid: {
      marginTop: 10,
      flexDirection: 'row',
      gap: 8,
    },
    emptyText: {
      paddingVertical: 6,
      textAlign: 'center',
      fontSize: 12,
      fontWeight: '800',
      color: colors.textSecondary,
    },
  });
