import { StyleSheet } from 'react-native';
import type { AppColors } from '@/shared/theme/colors';

export const managerStylesBase = StyleSheet.create({
  donutWrap: {
    width: 128,
    height: 128,
    alignItems: 'center',
    justifyContent: 'center',
  },
  donutCenter: {
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugeWrap: {
    height: 122,
    alignItems: 'center',
    justifyContent: 'center',
  },
  gaugeValue: {
    position: 'absolute',
    top: 56,
    alignItems: 'center',
  },
  outletCircleMetric: {
    alignItems: 'center',
    gap: 5,
  },
  outletCircleValueWrap: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outletCircleValue: {
    fontSize: 14,
    fontWeight: '800',
  },
  outletCircleLabel: {
    fontSize: 11,
    fontWeight: '700',
  },
});

export const createManagerStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundSecondary,
    },
    scrollContent: {
      paddingHorizontal: 14,
      paddingTop: 14,
      paddingBottom: 28,
      gap: 14,
    },
    headerPanel: {
      backgroundColor: colors.surface,
      borderRadius: 12,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.border,
      gap: 12,
    },
    summaryFilterRow: {
      gap: 8,
      paddingRight: 4,
    },
    skeletonFilterRow: {
      flexDirection: 'row',
      gap: 8,
    },
    summaryFilterChip: {
      minWidth: 72,
      paddingHorizontal: 13,
      paddingVertical: 8,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.border,
      backgroundColor: colors.backgroundSecondary,
      alignItems: 'center',
    },
    summaryFilterChipActive: {
      borderColor: colors.primary,
      backgroundColor: colors.primary,
    },
    summaryFilterText: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    summaryFilterTextActive: {
      color: colors.primaryContrast,
    },
    header: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    headerIdentity: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    headerAvatar: {
      width: 42,
      height: 42,
      borderRadius: 21,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary + '14',
      borderWidth: 1,
      borderColor: colors.primary + '22',
    },
    headerAvatarText: {
      fontSize: 13,
      fontWeight: '900',
      color: colors.primary,
    },
    eyebrow: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textTertiary,
      textTransform: 'uppercase',
      letterSpacing: 0,
    },
    title: {
      fontSize: 22,
      fontWeight: '900',
      color: colors.textPrimary,
      marginTop: 2,
    },
    headerRangeButton: {
      width: 40,
      height: 40,
      borderRadius: 20,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.border,
    },
    filterButton: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
    },
    sectionHeader: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      gap: 10,
      paddingHorizontal: 2,
      marginTop: 2,
    },
    skeletonSectionHeader: {
      flexDirection: 'row',
      alignItems: 'flex-end',
      justifyContent: 'space-between',
      gap: 10,
      paddingHorizontal: 2,
      marginTop: 2,
    },
    skeletonLineGap: {
      marginTop: 7,
    },
    sectionTitle: {
      fontSize: 15,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    sectionSubtitle: {
      fontSize: 11,
      fontWeight: '600',
      color: colors.textTertiary,
      marginTop: 2,
    },
    sectionBadge: {
      fontSize: 10,
      fontWeight: '900',
      color: colors.primary,
      backgroundColor: colors.infoLight,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 7,
      overflow: 'hidden',
    },
    summaryGrid: {
      flexDirection: 'column',
      gap: 10,
    },
    card: {
      flex: 1,
      backgroundColor: colors.surface,
      borderRadius: 10,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.border,
    },
    outletSummaryCard: {
      flexGrow: 0,
      flexShrink: 0,
      flexBasis: 'auto',
      overflow: 'hidden',
    },
    outletSummaryContent: {
      flexDirection: 'row',
      alignItems: 'stretch',
      gap: 14,
    },
    outletSummaryList: {
      flex: 1,
      minWidth: 0,
      justifyContent: 'space-between',
      gap: 12,
    },
    outletCompactRow: {
      gap: 6,
    },
    outletCompactHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    outletCompactLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    outletCompactValue: {
      fontSize: 13,
      fontWeight: '900',
      color: colors.textPrimary,
      flexShrink: 1,
    },
    outletMetricPanel: {
      width: 146,
      borderLeftWidth: 1,
      borderLeftColor: colors.borderLight,
      paddingLeft: 12,
      gap: 12,
    },
    outletMetricTitle: {
      fontSize: 13,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    productivityMetricRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 6,
    },
    productivityCounts: {
      flex: 1,
      minWidth: 0,
    },
    productivityCountLabel: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    productivityCountValue: {
      fontSize: 12,
      fontWeight: '900',
      color: colors.textPrimary,
      marginBottom: 4,
    },
    outletBottomMetrics: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 6,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
      marginBottom: 8,
    },
    headerText: {
      flex: 1,
    },
    cardTitle: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    cardMeta: {
      fontSize: 10,
      fontWeight: '600',
      color: colors.textTertiary,
      marginTop: 2,
    },
    summaryRow: {
      minHeight: 34,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    skeletonSummaryRow: {
      minHeight: 34,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    summaryLabelWrap: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingRight: 4,
    },
    statusDot: {
      width: 7,
      height: 7,
      borderRadius: 4,
    },
    summaryLabel: {
      flex: 1,
      fontSize: 11,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    summaryValue: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    totalRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingTop: 9,
    },
    totalLabel: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    totalValue: {
      fontSize: 13,
      fontWeight: '900',
      color: colors.primary,
    },
    callCircleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-around',
      gap: 10,
      marginBottom: 10,
    },
    callCircleItem: {
      alignItems: 'center',
      gap: 5,
    },
    callCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.success,
    },
    callCircleMuted: {
      width: 64,
      height: 64,
      borderRadius: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 3,
      borderColor: colors.border,
    },
    callValue: {
      fontSize: 15,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    callLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textSecondary,
      textAlign: 'center',
    },
    callMetrics: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    metricItem: {
      alignItems: 'center',
      flex: 1,
      minHeight: 42,
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: colors.backgroundSecondary,
    },
    metricValue: {
      fontSize: 12,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    metricLabel: {
      fontSize: 10,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    orderValue: {
      borderRadius: 10,
      backgroundColor: colors.primary,
      paddingVertical: 8,
      alignItems: 'center',
    },
    orderValueLabel: {
      fontSize: 9,
      fontWeight: '700',
      color: colors.primaryContrast,
      opacity: 0.85,
    },
    orderValueText: {
      fontSize: 20,
      fontWeight: '900',
      color: colors.primaryContrast,
    },
    targetHint: {
      minHeight: 34,
      borderRadius: 10,
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.primary,
    },
    targetHintMuted: {
      backgroundColor: colors.backgroundSecondary,
    },
    targetHintText: {
      flex: 1,
      fontSize: 10,
      fontWeight: '700',
      color: colors.primaryContrast,
    },
    targetHintTextMuted: {
      color: colors.textTertiary,
    },
    mtdBadge: {
      fontSize: 10,
      fontWeight: '900',
      color: colors.primary,
      backgroundColor: colors.infoLight,
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 7,
      overflow: 'hidden',
    },
    metricToggle: {
      flexDirection: 'row',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.backgroundSecondary,
      overflow: 'hidden',
      marginBottom: 10,
    },
    metricToggleItem: {
      flex: 1,
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    metricToggleItemActive: {
      backgroundColor: colors.primary,
    },
    metricToggleText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    metricToggleTextActive: {
      color: colors.primaryContrast,
    },
    chartRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
    },
    skeletonChartRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      marginTop: 10,
    },
    skeletonGauge: {
      alignSelf: 'center',
      marginVertical: 9,
    },
    chartEmptyText: {
      flex: 1,
      textAlign: 'center',
      fontSize: 12,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    legend: {
      flex: 1,
      gap: 8,
    },
    legendRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    legendTextWrap: {
      flex: 1,
    },
    legendLabel: {
      fontSize: 11,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    legendValue: {
      fontSize: 9,
      fontWeight: '600',
      color: colors.textTertiary,
    },
    legendPercent: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    routeInfo: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      marginBottom: 12,
      padding: 10,
      borderRadius: 10,
      backgroundColor: colors.backgroundSecondary,
    },
    avatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary + '18',
    },
    avatarText: {
      fontSize: 11,
      fontWeight: '900',
      color: colors.primary,
    },
    routeName: {
      fontSize: 12,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    progressLegend: {
      flexDirection: 'row',
      gap: 16,
      marginBottom: 8,
    },
    progressLegendItem: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
    },
    progressTrack: {
      height: 28,
      borderRadius: 7,
      backgroundColor: colors.backgroundTertiary,
      overflow: 'hidden',
      marginBottom: 8,
      justifyContent: 'center',
    },
    progressFill: {
      position: 'absolute',
      left: 0,
      top: 0,
      bottom: 0,
      borderRadius: 7,
    },
    progressText: {
      alignSelf: 'flex-end',
      paddingRight: 8,
      fontSize: 10,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    outletRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      minHeight: 52,
      paddingVertical: 6,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    outletText: {
      width: 88,
      minWidth: 0,
      overflow: 'hidden',
    },
    outletProgressTrack: {
      flex: 1,
      minWidth: 24,
      height: 6,
      borderRadius: 3,
      overflow: 'hidden',
      backgroundColor: colors.backgroundTertiary,
    },
    outletProgressFill: {
      height: '100%',
      borderRadius: 4,
    },
    percentBadge: {
      width: 38,
      height: 38,
      borderRadius: 19,
      flexShrink: 0,
      borderWidth: 2,
      alignItems: 'center',
      justifyContent: 'center',
    },
    percentBadgeText: {
      fontSize: 11,
      fontWeight: '900',
    },
  });
