import { StyleSheet } from 'react-native';
import type { AppColors } from '@/shared/theme/colors';

export const createManagerTargetsBaseStyles = (colors: AppColors) =>
  StyleSheet.create({
    metric: {
      flex: 1,
      minWidth: 0,
    },
    metricValue: {
      fontSize: 12,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    metricLabel: {
      marginTop: 3,
      fontSize: 10,
      fontWeight: '700',
      color: colors.textTertiary,
    },
  });

export const createManagerTargetsStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundSecondary,
    },
    content: {
      padding: 12,
      gap: 10,
      paddingBottom: 28,
    },
    heroBand: {
      minHeight: 64,
      backgroundColor: colors.surface,
      borderRadius: 10,
      padding: 12,
      borderWidth: 1,
      borderColor: colors.border,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    heroIcon: {
      width: 38,
      height: 38,
      borderRadius: 19,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.infoLight,
    },
    heroTitle: {
      fontSize: 15,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    parentBanner: {
      minHeight: 52,
      borderRadius: 10,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      backgroundColor: colors.infoLight,
      borderWidth: 1,
      borderColor: colors.border,
    },
    parentTextWrap: {
      flex: 1,
    },
    parentTitle: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    parentSubtitle: {
      marginTop: 2,
      fontSize: 11,
      fontWeight: '600',
      color: colors.textTertiary,
    },
    drillButton: {
      minHeight: 28,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      borderRadius: 7,
      paddingHorizontal: 8,
      backgroundColor: colors.infoLight,
    },
    metricToggle: {
      flexDirection: 'row',
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.borderLight,
      backgroundColor: colors.surface,
      overflow: 'hidden',
    },
    metricToggleItem: {
      flex: 1,
      minHeight: 34,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 8,
    },
    metricToggleItemActive: {
      backgroundColor: colors.primary,
    },
    metricToggleText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    metricToggleTextActive: {
      color: colors.primaryContrast,
    },
    userCard: {
      borderRadius: 10,
      padding: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.border,
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.12,
      shadowRadius: 3,
      elevation: 2,
    },
    userCardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 9,
      marginBottom: 12,
    },
    avatar: {
      width: 34,
      height: 34,
      borderRadius: 17,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primary + '18',
    },
    avatarText: {
      fontSize: 13,
      fontWeight: '900',
      color: colors.primary,
    },
    userTitleWrap: {
      flex: 1,
      minWidth: 0,
    },
    userName: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    userPosition: {
      marginTop: 2,
      fontSize: 10,
      fontWeight: '600',
      color: colors.textTertiary,
    },
    drillText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textQuaternary,
    },
    metricsRow: {
      flexDirection: 'row',
      gap: 14,
    },
    progressTrack: {
      marginTop: 10,
      height: 7,
      borderRadius: 4,
      backgroundColor: colors.backgroundTertiary,
      overflow: 'hidden',
    },
    progressFill: {
      height: '100%',
      borderRadius: 4,
      backgroundColor: colors.primary,
    },
    progressMetaRow: {
      marginTop: 6,
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
    },
    progressMetaText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    rateRow: {
      marginTop: 8,
      flexDirection: 'row',
      gap: 6,
      justifyContent: 'flex-end',
    },
    rateBadge: {
      borderRadius: 5,
      paddingHorizontal: 7,
      paddingVertical: 3,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    rateLabel: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    categoryButton: {
      marginTop: 14,
      minHeight: 26,
      borderRadius: 7,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 5,
      backgroundColor: colors.infoLight,
    },
    categoryButtonText: {
      fontSize: 10,
      fontWeight: '800',
      color: colors.primary,
    },
    categoryPanel: {
      marginTop: -4,
      borderRadius: 10,
      padding: 12,
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
      gap: 10,
    },
    categoryPanelHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    categoryPanelTitle: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    categoryPanelSubtitle: {
      marginTop: 2,
      fontSize: 10,
      fontWeight: '600',
      color: colors.textTertiary,
    },
    categoryPanelBadge: {
      borderRadius: 7,
      paddingHorizontal: 8,
      paddingVertical: 4,
      backgroundColor: colors.infoLight,
      color: colors.primary,
      fontSize: 10,
      fontWeight: '900',
      overflow: 'hidden',
    },
    categoryRow: {
      borderRadius: 8,
      padding: 10,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    categoryRowTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    categoryName: {
      flex: 1,
      fontSize: 12,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    categoryPercent: {
      fontSize: 10,
      fontWeight: '900',
      color: colors.primary,
    },
    categoryMetricsGrid: {
      marginTop: 10,
      flexDirection: 'row',
      gap: 8,
    },
    emptyText: {
      paddingVertical: 6,
      textAlign: 'center',
      fontSize: 12,
      fontWeight: '800',
      color: colors.textSecondary,
    },
  });
