import { StyleSheet } from 'react-native';
import type { AppColors } from '@/shared/theme/colors';

export const createManagerTeamCoverageStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundSecondary,
    },
    content: {
      flexGrow: 1,
      padding: 12,
      paddingBottom: 32,
    },
    card: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 12,
      gap: 12,
      flexGrow: 1,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    managerInfo: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    managerAvatar: {
      width: 34,
      height: 34,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${colors.primary}15`,
    },
    managerAvatarText: {
      color: colors.primary,
      fontSize: 12,
      fontWeight: '900',
    },
    managerTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    position: {
      color: colors.textTertiary,
      fontSize: 11,
      fontWeight: '700',
      marginTop: 2,
    },
    title: {
      color: colors.textPrimary,
      fontSize: 12,
      fontWeight: '900',
    },
    infoRow: {
      flexDirection: 'row',
      gap: 8,
    },
    infoCard: {
      flex: 1,
      minHeight: 72,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 8,
      paddingHorizontal: 10,
      paddingVertical: 8,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 0.5,
      borderColor: colors.borderLight,
    },
    infoIcon: {
      width: 30,
      height: 30,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${colors.primary}10`,
    },
    infoTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    infoLabel: {
      fontSize: 9,
      fontWeight: '900',
      color: colors.primary,
      textTransform: 'uppercase',
    },
    infoValue: {
      marginTop: 2,
      fontSize: 18,
      lineHeight: 22,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    grid: {
      flex: 1,
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    stat: {
      width: '48.6%',
      minHeight: 112,
      flexGrow: 1,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      paddingHorizontal: 6,
      paddingVertical: 8,
      backgroundColor: `${colors.primary}10`,
    },
    statIcon: {
      width: 34,
      height: 34,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
    },
    statValue: {
      color: colors.primary,
      fontSize: 20,
      lineHeight: 24,
      fontWeight: '900',
      marginTop: 8,
    },
    statLabel: {
      color: colors.textTertiary,
      fontSize: 11,
      fontWeight: '800',
      textAlign: 'center',
      marginTop: 3,
    },
  });
