import { Platform, StyleSheet } from 'react-native';
import type { AppColors } from '@/shared/theme/colors';

export const createManagerTeamCoverageStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundSecondary,
    },
    content: {
      flexGrow: 1,
      padding: 14,
      paddingBottom: 32,
      gap: 12,
    },
    skeletonLineGap: {
      marginTop: 7,
    },
    skeletonResourceIcon: {
      backgroundColor: colors.backgroundSecondary,
    },
    skeletonMetricIcon: {
      backgroundColor: colors.backgroundSecondary,
    },
    skeletonMetricValue: {
      marginTop: 12,
    },
    skeletonOverviewText: {
      flex: 1,
      minWidth: 0,
    },

    errorBanner: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      borderRadius: 8,
      paddingHorizontal: 12,
      paddingVertical: 10,
      backgroundColor: `${colors.error ?? '#C0392B'}14`,
      borderWidth: 0.5,
      borderColor: `${colors.error ?? '#C0392B'}40`,
    },
    errorBannerText: {
      flex: 1,
      fontSize: 12,
      fontWeight: '700',
      color: colors.error ?? '#C0392B',
    },

    overviewCard: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 14,
      gap: 12,
      ...cardShadow(colors),
    },
    overviewHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
    },
    overviewTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    overviewEyebrow: {
      color: colors.textTertiary,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    overviewValue: {
      color: colors.textPrimary,
      fontSize: 34,
      lineHeight: 39,
      fontWeight: '900',
      marginTop: 2,
    },
    overviewCaption: {
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700',
      marginTop: 2,
    },
    overviewIconWrap: {
      width: 56,
      height: 56,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${colors.primary}12`,
      borderWidth: 1,
      borderColor: `${colors.primary}20`,
    },
    progressTrack: {
      height: 8,
      overflow: 'hidden',
      borderRadius: 8,
      backgroundColor: colors.backgroundTertiary,
    },
    progressFill: {
      height: '100%',
      borderRadius: 8,
      backgroundColor: colors.primary,
    },
    overviewMetaRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 10,
    },
    overviewMetaText: {
      flex: 1,
      color: colors.textTertiary,
      fontSize: 11,
      lineHeight: 14,
      fontWeight: '700',
    },
    overviewMetaTextRight: {
      textAlign: 'right',
    },

    resourceSummary: {
      flexDirection: 'row',
      gap: 8,
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      padding: 8,
      ...cardShadow(colors),
    },
    resourceItem: {
      flex: 1,
      minHeight: 92,
      alignItems: 'center',
      justifyContent: 'center',
      gap: 7,
      borderRadius: 8,
      backgroundColor: colors.backgroundSecondary,
      paddingHorizontal: 6,
      paddingVertical: 10,
    },
    resourceIcon: {
      width: 34,
      height: 34,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.surface,
      borderWidth: 1,
      borderColor: colors.borderLight,
    },
    resourceTextBlock: {
      alignItems: 'center',
      alignSelf: 'stretch',
      minWidth: 0,
    },
    resourceValue: {
      color: colors.textPrimary,
      fontSize: 20,
      lineHeight: 24,
      fontWeight: '900',
      textAlign: 'center',
    },
    resourceLabel: {
      color: colors.textTertiary,
      fontSize: 11,
      fontWeight: '700',
      marginTop: 3,
      textAlign: 'center',
    },

    metricsPanel: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 1,
      borderColor: colors.border,
      paddingHorizontal: 12,
      paddingVertical: 4,
      ...cardShadow(colors),
    },
    metricRow: {
      minHeight: 60,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    metricIcon: {
      width: 34,
      height: 34,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${colors.primary}14`,
    },
    metricTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    metricValue: {
      color: colors.textPrimary,
      fontSize: 19,
      lineHeight: 23,
      fontWeight: '900',
      textAlign: 'right',
    },
    metricLabel: {
      color: colors.textSecondary,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 16,
    },
    metricDivider: {
      height: 1,
      marginLeft: 42,
      backgroundColor: colors.borderLight,
    },

    modalOverlay: {
      flex: 1,
      justifyContent: 'flex-end',
      backgroundColor: colors.overlay,
    },
    modalBackdrop: {
      ...StyleSheet.absoluteFillObject,
    },
    detailModal: {
      maxHeight: '76%',
      minHeight: 300,
      borderTopLeftRadius: 8,
      borderTopRightRadius: 8,
      backgroundColor: colors.surface,
      paddingTop: 8,
      overflow: 'hidden',
    },
    modalHandle: {
      alignSelf: 'center',
      width: 38,
      height: 4,
      borderRadius: 4,
      backgroundColor: colors.border,
      marginBottom: 10,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      paddingHorizontal: 16,
      paddingBottom: 14,
      borderBottomWidth: 1,
      borderBottomColor: colors.borderLight,
    },
    modalTitleBlock: {
      flex: 1,
      minWidth: 0,
    },
    modalTitle: {
      color: colors.textPrimary,
      fontSize: 17,
      lineHeight: 22,
      fontWeight: '900',
    },
    modalSubtitle: {
      color: colors.textTertiary,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '700',
      marginTop: 2,
    },
    modalCloseButton: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.backgroundSecondary,
    },
    modalListContent: {
      paddingHorizontal: 16,
      paddingVertical: 8,
    },
    modalEmptyContent: {
      flexGrow: 1,
      justifyContent: 'center',
      paddingHorizontal: 16,
      paddingVertical: 24,
    },
    modalRow: {
      minHeight: 62,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingVertical: 10,
    },
    modalRowIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: `${colors.primary}12`,
    },
    modalRowTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    modalRowTitle: {
      color: colors.textPrimary,
      fontSize: 14,
      lineHeight: 18,
      fontWeight: '800',
    },
    modalRowSubtitle: {
      color: colors.textTertiary,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '600',
      marginTop: 2,
    },
    modalRowMeta: {
      maxWidth: 96,
      color: colors.textSecondary,
      fontSize: 12,
      lineHeight: 16,
      fontWeight: '800',
      textAlign: 'right',
    },
    modalRowDivider: {
      height: 1,
      marginLeft: 46,
      backgroundColor: colors.borderLight,
    },
    modalEmptyState: {
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
    },
    modalEmptyText: {
      color: colors.textTertiary,
      fontSize: 13,
      lineHeight: 18,
      fontWeight: '700',
    },
  });

const cardShadow = (colors: AppColors) =>
  Platform.select({
    ios: {
      shadowColor: colors.shadow,
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.06,
      shadowRadius: 3,
    },
    android: {
      elevation: 1,
    },
    default: {},
  });
