import { StyleSheet } from 'react-native';
import type { AppColors } from '@/shared/theme/colors';

const managerFontSize = {
  xs: 10,
  sm: 12,
  base: 14,
  lg: 17,
};

export const createBaseStyles = (colors: AppColors) =>
  StyleSheet.create({
    summaryMetric: {
      width: '31.8%',
      minHeight: 68,
      justifyContent: 'space-between',
      borderRadius: 6,
      padding: 8,
      marginRight: '1.5%',
      marginBottom: 6,
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 0.5,
      borderColor: colors.borderLight,
    },
    summaryMetricTop: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    summaryMarker: {
      width: 18,
      height: 3,
      borderRadius: 3,
    },
    summaryValue: {
      marginTop: 6,
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    summaryLabel: {
      marginTop: 6,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
      textTransform: 'uppercase',
    },
    userStat: {
      flex: 1,
      minHeight: 42,
      justifyContent: 'center',
      borderRadius: 6,
      paddingHorizontal: 4,
      backgroundColor: colors.backgroundSecondary,
      minWidth: 0,
    },
    userStatValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    userStatLabel: {
      marginTop: 2,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
      textAlign: 'center',
    },
  });

export const createManagerDailySummaryStyles = (colors: AppColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.backgroundSecondary,
    },
    content: {
      padding: 12,
      paddingBottom: 24,
      gap: 10,
    },
    dailyHeader: {
      minHeight: 56,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      borderRadius: 8,
      padding: 12,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    dailyHeaderMain: {
      flex: 1,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      minWidth: 0,
    },
    dailyIcon: {
      width: 36,
      height: 36,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    dailyHeaderText: {
      flex: 1,
      minWidth: 0,
    },
    sectionTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textTertiary,
      letterSpacing: 0,
    },
    dailyTitle: {
      marginTop: 2,
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    summaryCard: {
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 12,
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 12,
      marginBottom: 8,
    },
    managerInfo: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    managerAvatar: {
      width: 38,
      height: 38,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    managerAvatarText: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.surface,
    },
    managerTextBlock: {
      flex: 1,
      minWidth: 0,
    },
    cardTitle: {
      marginTop: 2,
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    linkButton: {
      minHeight: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 6,
      paddingHorizontal: 14,
      backgroundColor: colors.surface,
    },
    linkText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.primary,
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      marginTop: 8,
      marginRight: '-1.5%',
    },
    metricToggle: {
      flexDirection: 'row',
      marginTop: 8,
      borderRadius: 6,
      borderWidth: 0.5,
      borderColor: colors.borderLight,
      backgroundColor: colors.backgroundSecondary,
      overflow: 'hidden',
    },
    metricToggleItem: {
      flex: 1,
      minHeight: 30,
      alignItems: 'center',
      justifyContent: 'center',
      paddingHorizontal: 6,
    },
    metricToggleItemActive: {
      backgroundColor: colors.primary,
    },
    metricToggleText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    metricToggleTextActive: {
      color: colors.primaryContrast,
    },
    searchRow: {
      height: 40,
      borderRadius: 8,
      paddingHorizontal: 12,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    searchInput: {
      flex: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textPrimary,
      paddingVertical: 0,
    },
    listHeaderRow: {
      minHeight: 24,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 2,
      marginBottom: 4,
    },
    listHeaderTitle: {
      fontSize: 15,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    listHeaderMeta: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    userCard: {
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 10,
      gap: 8,
      marginBottom: 8,
    },
    userCardDisabled: {
      borderColor: colors.borderLight,
      backgroundColor: colors.backgroundSecondary,
    },
    userHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    userIdentity: {
      flex: 1,
      minWidth: 0,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    userAvatar: {
      width: 34,
      height: 34,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    userAvatarText: {
      fontSize: 12,
      fontWeight: '900',
      color: colors.surface,
    },
    userNameBlock: {
      flex: 1,
      minWidth: 0,
    },
    userName: {
      fontSize: 14,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    userPosition: {
      marginTop: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '600',
      color: colors.textSecondary,
    },
    iconActions: {
      flexDirection: 'row',
      gap: 8,
    },
    whatsappButton: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: '#25D36615',
      borderWidth: 0.5,
      borderColor: '#25D366',
    },
    callButton: {
      width: 32,
      height: 32,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 8,
      backgroundColor: `${colors.primary}15`,
      borderWidth: 0.5,
      borderColor: colors.primary,
    },
    routeBadge: {
      minHeight: 28,
      borderWidth: 0.5,
      flexDirection: 'row',
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderRadius: 6,
      overflow: 'hidden',
    },
    routeBadgeText: {
      width: '35%',
      minHeight: 28,
      textAlignVertical: 'center',
      textAlign: 'center',
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      backgroundColor: colors.backgroundSecondary,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      color: colors.textPrimary,
    },
    routeText: {
      flex: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    locationText: {
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    userUnavailableText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    userStats: {
      flexDirection: 'row',
      gap: 6,
    },
    emptyText: {
      paddingVertical: 16,
      textAlign: 'center',
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    timelineHeader: {
      borderRadius: 8,
      padding: 10,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    timelineTitleRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
    },
    timelineTitleText: {
      flex: 1,
      minWidth: 0,
    },
    tabsRow: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    tabItem: {
      flex: 1,
      minHeight: 34,
      alignItems: 'center',
      justifyContent: 'center',
      borderBottomWidth: 2,
      borderBottomColor: 'transparent',
    },
    tabItemActive: {
      borderBottomColor: colors.info,
    },
    tabText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textTertiary,
    },
    tabTextActive: {
      color: colors.info,
    },
    routeInfoCard: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 10,
      borderWidth: 0.5,
      borderColor: colors.border,
      gap: 6,
    },
    statusBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      alignSelf: 'flex-start',
      paddingHorizontal: 8,
      paddingVertical: 3,
      borderRadius: 12,
      gap: 4,
    },
    statusDot: {
      width: 6,
      height: 6,
      borderRadius: 3,
    },
    statusText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
    },
    routeInfoRow: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    routeInfoText: {
      flex: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    locationAction: {
      minHeight: 26,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 6,
      backgroundColor: colors.infoLight,
      borderWidth: 0.5,
      borderColor: colors.info,
    },
    locationActionDisabled: {
      backgroundColor: colors.backgroundSecondary,
      borderColor: colors.border,
    },
    locationActionText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.info,
    },
    locationActionTextDisabled: {
      color: colors.textTertiary,
    },
    userStatsSummary: {
      flexDirection: 'row',
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: colors.border,
      paddingVertical: 8,
    },
    userStatItem: {
      flex: 1,
      alignItems: 'center',
    },
    userStatItemValue: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    userStatItemLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textTertiary,
      marginTop: 2,
    },
    userStatDivider: {
      width: 0.5,
      backgroundColor: colors.border,
    },
    timeline: {
      paddingLeft: 16,
      gap: 12,
    },
    timelineLine: {
      position: 'absolute',
      left: 22,
      top: 0,
      bottom: 0,
      width: 1,
      backgroundColor: colors.border,
    },
    dayStartContainer: {
      position: 'relative',
      marginBottom: 4,
    },
    dayStartCard: {
      marginLeft: 14,
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    dayStartContent: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      padding: 12,
      gap: 12,
    },
    dayStartInfo: {
      flex: 1,
    },
    dayStartTitle: {
      fontSize: 11,
      fontWeight: '700',
      color: colors.textSecondary,
      letterSpacing: 0,
    },
    dayStartTime: {
      marginTop: 4,
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    selfieContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
    },
    selfieButton: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      backgroundColor: colors.primary,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 6,
    },
    selfieButtonText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.primaryContrast,
    },
    dayStartImage: {
      width: 44,
      height: 44,
      borderRadius: 8,
      backgroundColor: colors.borderLight,
    },
    dayStartImagePlaceholder: {
      width: 44,
      height: 44,
      borderRadius: 8,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.backgroundSecondary,
      borderWidth: 0.5,
      borderColor: colors.borderLight,
    },
    timelineDot: {
      position: 'absolute',
      left: 2,
      top: 16,
      width: 20,
      height: 20,
      borderRadius: 10,
      backgroundColor: colors.surface,
      alignItems: 'center',
      justifyContent: 'center',
      zIndex: 1,
    },
    activityCardWrapper: {
      position: 'relative',
      marginBottom: 4,
    },
    timelineDotSmall: {
      position: 'absolute',
      left: 2,
      top: 20,
      width: 12,
      height: 12,
      borderRadius: 6,
      backgroundColor: colors.infoLight,
      borderWidth: 2,
      borderColor: colors.info,
      zIndex: 1,
    },
    activityCard: {
      marginLeft: 14,
      borderRadius: 8,
      padding: 10,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    activityHeader: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 8,
      marginBottom: 8,
    },
    activityHeaderLeft: {
      flex: 1,
    },
    activityTitle: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textSecondary,
    },
    activityTime: {
      marginTop: 2,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    duration: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    outletRow: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      gap: 8,
      marginBottom: 8,
    },
    outletName: {
      flex: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    ownerName: {
      maxWidth: '38%',
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    activityLocationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      flexWrap: 'wrap',
      gap: 6,
      marginBottom: 8,
    },
    activityLocationTextWrap: {
      flex: 1,
      minWidth: 96,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
    },
    activityLocationText: {
      flex: 1,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    metricGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 5,
    },
    metricCell: {
      width: '31.8%',
      minHeight: 46,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 4,
      borderRadius: 6,
      backgroundColor: colors.backgroundSecondary,
    },
    metricValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    metricLabel: {
      marginTop: 2,
      textAlign: 'center',
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    orderScreen: {
      gap: 8,
    },
    orderHero: {
      minHeight: 68,
      paddingHorizontal: 12,
      paddingVertical: 10,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      gap: 10,
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    orderHeroText: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderHeroSub: {
      marginTop: 4,
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textSecondary,
    },
    orderHeroRight: {
      alignItems: 'flex-end',
      minWidth: 80,
    },
    orderHeroValue: {
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.success,
    },
    orderOutlet: {
      paddingHorizontal: 4,
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderCategory: {
      overflow: 'hidden',
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    orderCategoryHeader: {
      minHeight: 38,
      paddingHorizontal: 8,
      paddingVertical: 6,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      gap: 8,
    },
    orderCategoryHeaderBlue: {
      backgroundColor: colors.infoLight,
    },
    orderCategoryHeaderMuted: {
      backgroundColor: colors.backgroundSecondary,
    },
    orderCategoryName: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderCategoryMeta: {
      marginTop: 2,
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    orderCategoryValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderLine: {
      paddingHorizontal: 8,
      paddingVertical: 8,
      borderTopWidth: 0.5,
      borderTopColor: colors.borderLight,
      backgroundColor: colors.surface,
    },
    orderLineName: {
      fontSize: managerFontSize.sm,
      lineHeight: 16,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderLineMeta: {
      marginTop: 6,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      flexWrap: 'wrap',
    },
    orderLineMetaText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textTertiary,
    },
    orderUnitPill: {
      minHeight: 14,
      paddingHorizontal: 6,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 4,
      backgroundColor: colors.borderLight,
    },
    orderUnitPillText: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textSecondary,
    },
    orderLineValue: {
      marginLeft: 'auto',
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textSecondary,
    },
    orderSummary: {
      marginTop: 2,
      borderRadius: 8,
      backgroundColor: colors.surface,
      borderWidth: 0.5,
      borderColor: colors.border,
      overflow: 'hidden',
    },
    orderSummaryHeader: {
      minHeight: 30,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: colors.primaryLight,
    },
    orderSummaryHeaderText: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.primary,
    },
    orderSummaryRow: {
      minHeight: 30,
      paddingHorizontal: 10,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    orderSummaryLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.textPrimary,
    },
    orderSummaryValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    orderDiscountLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.error,
    },
    orderDiscountValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.error,
    },
    orderDivider: {
      height: 0.5,
      marginVertical: 2,
      backgroundColor: colors.border,
    },
    orderPayableLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.success,
    },
    orderPayableValue: {
      fontSize: managerFontSize.xs,
      fontWeight: '900',
      color: colors.success,
    },

    // Add these to your createManagerDailySummaryStyles function

    // MTD Tab Styles
    mtdContainer: {
      gap: 12,
    },
    mtdHeader: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    mtdHeaderTitle: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    mtdHeaderSubtitle: {
      marginTop: 4,
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    mtdGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    mtdCard: {
      width: '48%',
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 10,
      borderWidth: 0.5,
      borderColor: colors.border,
    },
    mtdCardLabel: {
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textTertiary,
      marginBottom: 4,
    },
    mtdCardValue: {
      fontSize: managerFontSize.base,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    // Route Tab Styles
    routeContainer: {
      gap: 12,
    },
    routeHeader: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      padding: 12,
      borderWidth: 0.5,
      borderColor: colors.border,
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    routeHeaderLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
    },
    routeHeaderTitle: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    routeProgress: {
      backgroundColor: colors.primaryLight,
      paddingHorizontal: 8,
      paddingVertical: 4,
      borderRadius: 12,
    },
    routeProgressText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
      color: colors.primary,
    },
    routeTimeline: {
      backgroundColor: colors.surface,
      borderRadius: 8,
      borderWidth: 0.5,
      borderColor: colors.border,
      padding: 12,
    },
    routeStopItem: {
      flexDirection: 'row',
      marginBottom: 16,
    },
    routeStopLine: {
      width: 24,
      alignItems: 'center',
      position: 'relative',
    },
    routeLineTop: {
      position: 'absolute',
      top: -16,
      width: 1,
      height: 16,
      backgroundColor: colors.border,
    },
    routeLineBottom: {
      position: 'absolute',
      top: 20,
      width: 1,
      height: 40,
      backgroundColor: colors.border,
    },
    routeStopContent: {
      flex: 1,
      backgroundColor: colors.backgroundSecondary,
      borderRadius: 8,
      padding: 10,
      marginLeft: 8,
    },
    routeStopHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 4,
    },
    routeStopName: {
      fontSize: managerFontSize.sm,
      fontWeight: '900',
      color: colors.textPrimary,
    },
    routeStopType: {
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textTertiary,
    },
    routeStopTime: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      marginBottom: 4,
    },
    routeStopTimeText: {
      fontSize: managerFontSize.xs,
      fontWeight: '700',
      color: colors.textSecondary,
    },
    routeStopStatus: {
      marginTop: 4,
    },
    routeStopStatusText: {
      fontSize: managerFontSize.xs,
      fontWeight: '800',
    },
  });
