export const ENTITY_TABLES = {
  customers: 'customers',
  outlets: 'outlets',
  products: 'products',
  categories: 'categories',
  priceLists: 'price_lists',
  vans: 'vans',
  routes: 'routes',
  routeSessions: 'route_sessions',
  salesmen: 'salesmen',
  stock: 'stock',
  promotions: 'promotions',
  orders: 'orders',
  orderItems: 'order_items',
  collections: 'collections',
  attendance: 'attendance',
  activities: 'activities',
  visits: 'visits',
  nonSales: 'non_sales',
  leaves: 'leaves',
  surveys: 'surveys',
  expenses: 'expenses',
  returns: 'returns_data',
  complaints: 'complaints',
  targets: 'targets',
  vanDailyStock: 'van_daily_stock',
  mediaUploads: 'media_uploads',
} as const;

export type EntityName = keyof typeof ENTITY_TABLES;
export type EntityTable = (typeof ENTITY_TABLES)[EntityName];
export const MASTER_ENTITIES: EntityName[] = [
  'customers',
  'outlets',
  'products',
  'categories',
  'priceLists',
  'vans',
  'routes',
  'routeSessions',
  'salesmen',
  'stock',
  'promotions',
  'targets',
  'vanDailyStock',
];
export const TRANSACTION_ENTITIES: EntityName[] = [
  'orders',
  'orderItems',
  'collections',
  'attendance',
  'activities',
  'visits',
  'nonSales',
  'leaves',
  'surveys',
  'expenses',
  'returns',
  'complaints',
  'mediaUploads',
];
