import { BaseRepository } from './base.repository';

export const repositories = {
  customers: new BaseRepository('customers'),
  outlets: new BaseRepository('outlets'),
  products: new BaseRepository('products'),
  categories: new BaseRepository('categories'),
  priceLists: new BaseRepository('priceLists'),
  routes: new BaseRepository('routes'),
  vans: new BaseRepository('vans'),
  routeSessions: new BaseRepository('routeSessions'),
  salesmen: new BaseRepository('salesmen'),
  stock: new BaseRepository('stock'),
  promotions: new BaseRepository('promotions'),
  orders: new BaseRepository('orders'),
  orderItems: new BaseRepository('orderItems'),
  collections: new BaseRepository('collections'),
  attendance: new BaseRepository('attendance'),
  activities: new BaseRepository('activities'),
  visits: new BaseRepository('visits'),
  nonSales: new BaseRepository('nonSales'),
  leaves: new BaseRepository('leaves'),
  surveys: new BaseRepository('surveys'),
  expenses: new BaseRepository('expenses'),
  returns: new BaseRepository('returns'),
  complaints: new BaseRepository('complaints'),
  targets: new BaseRepository('targets'),
  vanDailyStock: new BaseRepository('vanDailyStock'),
  mediaUploads: new BaseRepository('mediaUploads'),
} as const;
